[project]
name = "PlayGround"
version = "0.1.0"
description = ""
authors = [
    {name = "Raf Blanckaert",email = "R.Blanckaert@outlook.com"}
]
readme = "README.md"
requires-python = ">=3.10,<3.13"

[tool.poetry.dependencies]
pandas = "^2.2"
numpy = "<2.0.0"
ipykernel = "^7.1"
seaborn = "^0.13"
matplotlib = "^3.9"
scikit-learn = "^1.4"
xgboost = "^2.0"
catboost = "^1.2"
lightgbm = "^4.0"
fastparquet = "^2024"
shapely = "^2.0"
optuna =  "^4.7.0"
optuna-integration = "*"
torch = "^2.10.0"
tensorflow = "^2.20.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
