work_dir = "C:/Users/Blanc/DataScientist/Kaggle/PlayGround/S5E11/kaggle/working/"
data_dir = "C:/Users/Blanc/DataScientist/Kaggle/PlayGround/S5E11/kaggle/input/"
svg_dir = "C:/Users/Blanc/DataScientist/Kaggle/PlayGround/S5E11/kaggle/svg/"
submissions_dir = work_dir + "submissions/"
model_dir = work_dir + "model/"
model_pred_train_dir = model_dir + "train_prediction/"
model_pred_test_dir = model_dir + "test_prediction/"
params_dir = "C:/Users/Blanc/DataScientist/Kaggle/PlayGround/S5E11/kaggle/working/params/"
